### ISSUE TITLE
address_standardizer.control file is missing

### ISSUE THREAD

**Issue by volkanunsal** [appropriate/docker-postgis#105]
In the Alpine build, the `address_standardizer.control` file seems to be missing in `/usr/local/share/postgresql/extension/`. I can't find it anywhere else in the system either.

**Comment by volkanunsal** [comment]
@md5 I believe the issue was these packages need to be installed for it to be configured:

```
pcre
pcre-dev
```

**Comment by saeed-vayghan** [comment]
@volkanunsal 
Could please describe your solution?
This is my docker-compose.yml

```
version: '3'

services:
  postgres:
    container_name: 'postgres-rechat-server'
    image: 'mdillon/postgis:10-alpine'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'changeme'
      PGDATA: '/data/postgres'
    volumes:
       - './postgres:/data/postgres'
    ports:
      - '5432:5432'
    networks:
      - 'postgres'
    restart: 'always'
```

How does it possible to enable `address_standardizer` extension?
