### ISSUE TITLE
ADD failed: stat /var/lib/docker/tmp/docker-builder821292538/.env/pip.conf: no such file or directory

### ISSUE THREAD

**Issue by realmhamdy** [appropriate/docker-postgis#150]
My build fails like this:
```
Step 8/14 : ADD .env/pip.conf /root/.pip/pip.conf
ERROR: Service 'postgresql' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder821292538/.env/pip.conf: no such file or directory
```

I have a basic section in `docker-compose.yml` that looks like this:
```
 postgresql:
    image: mdillon/postgis:latest
    build:
      context: ./
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=database
```
Any help will get this virtual cake 🎂.
