### ISSUE TITLE
docker-compose ?

### ISSUE THREAD

**Issue by hopewise** [appropriate/docker-postgis#19]
Hi,

I am very new to docker, and I did this docker-compose.yml file to make it easy to start the container:

```
postgis:
    image: mdillon/postgis
    volumes:
        - C:\Users\Sabri\Documents\postgis-data-folder:/var/lib/postgresql/data

    env_file: .postgis_env

    ports:
        - "9090:9000"
        - "54320:5432"
    links:
      - database
    container_name: postgis

database:
  image: postgres:9.4.4
  env_file: .env
  environment:
    LC_ALL: C.UTF-8
  container_name: postgres_database

```

it worked fine, and I could connect to db using 192.168.99.100:54320
however, do I need to link to image postgres:9.4.4 ? 
I've noticed that I have stopped the postgres_database container, and my app worked normally, please advice!

Also, how would I check the database file?  for ex: size ? where is it stored?

Thank you
