### ISSUE TITLE
Mounting volume on /docker-entrypoint.d prevents postgis initialization

### ISSUE THREAD

**Issue by johnktims** [appropriate/docker-postgis#35]
I'm using docker-compose and I'd like to run some `.sql` files when the container starts up, but that conflicts with `COPY ./initdb-postgis.sh /docker-entrypoint-initdb.d/postgis.sh` in the `Dockerfile`.

```
  postgresql:
    image: mdillon/postgis:latest
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
```

From what I've read, this is the expected behavior for docker volumes so I don't think this is a bug in your project, but I'm wondering if you're aware of a workaround.
