### ISSUE TITLE
docker-entrypoint-initdb.d after CREATE EXTENSIONs

### ISSUE THREAD

**Issue by juancaacuna** [appropriate/docker-postgis#74]
Guys, I need some help. I'm using `docker-compose`.
How do I run the `docker-entrypoint-initdb.d` script **after** Postgis EXTENSIONs are created?
Or maybe there is a different way of locating and naming my init script?

`docker-compose.yml:`
```
services:
  postgis:
    image: mdillon/postgis:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: postgis
    ports:
      - "5432:5432"
    env_file:
      - .env
```

`init.sql` is a SQL file I have in the **root** of the project, with a table creation, using a `GEOGRAPHY` column.

```
CREATE TABLE public."addresses"(
    "address_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "coordinates" GEOGRAPHY(POINT) NULL
);
```

`init.sql` currently fails, because `EXTENSIONs` are created **after** the script is run.

*ERROR:*
```
psql:/docker-entrypoint-initdb.d/init.sql:4: ERROR:  type "geography" does not exist
postgis | LINE 3:     "coordinates" GEOGRAPHY(POINT) NULL,
```

Thanks!

**Comment by ImreSamu** [comment]
based on [postgres-docker-documentation](https://github.com/docker-library/docs/tree/master/postgres)
_"These initialization files will be executed in sorted name order as defined by the current locale, ... "_
so probably  you need to rename from `init.sql` to `x_init.sql`

**Comment by juancaacuna** [comment]
Works!!! Thank you @ImreSamu !!

```
services:
  postgis:
    image: mdillon/postgis:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/x_init.sql
    container_name: postgis
    ports:
      - "5432:5432"
    env_file:
      - .env
```
