### ISSUE TITLE
Unable to access function PostGIS_Lib_Version

### ISSUE THREAD

**Issue by vincentchalamon** [appropriate/docker-postgis#76]
Hello,

I'm trying to implement PostGIS in my project, using your image `mdillon/postgis:10-alpine` and [jsor/doctrine-postgis](https://github.com/jsor/doctrine-postgis/) PHP library. It tries to use `PostGIS_Lib_Version()` function, but I have the following error:

<img width="746" alt="capture d ecran 2017-12-27 a 14 57 03" src="https://user-images.githubusercontent.com/407859/34383561-3e40e948-eb16-11e7-945b-a27fd78b288e.png">

Here is a part of my docker configuration:
```yaml
version: '3'

services:
  # ...
  db:
    image: mdillon/postgis:10-alpine
    healthcheck:
      test: chmod +x /usr/local/bin/healthcheck && /usr/local/bin/healthcheck
    environment:
      - POSTGRES_DB=api_platform
      - POSTGRES_PASSWORD=api_platform
    volumes:
      - ./docker/postgres/healthcheck.sh:/usr/local/bin/healthcheck:rw
```

I also tried to execute `update-postgis.sh` script, but everything seems ok:
```bash
docker exec -e POSTGRES_USER=postgres db update-postgis.sh
```
<img width="674" alt="capture d ecran 2017-12-27 a 15 08 29" src="https://user-images.githubusercontent.com/407859/34383756-d65236a0-eb17-11e7-9a63-613722291943.png">

Is there anything I missed?
