### ISSUE TITLE
docker volumes ERROR 

### ISSUE THREAD

**Issue by lclpedro** [appropriate/docker-postgis#89]
Error sharing volumes
```
postgis_1   | FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
postgis_1   | HINT:  The server must be started by the user that owns the data directory.
```
Exist solutions for error? | postgres 9.6 

docker-compose
```
version: "3"
services:
    postgis:
        image: mdillon/postgis:9.6
        environment:
            POSTGRES_USER: usertest
            POSTGRES_PASSWORD: usertest
            POSTGRES_DB: db_engenhagro
            PGDATA: /var/lib/postgresql/data
        ports:
            - 5432:5432
        volumes:
            - .data_postgres:/var/lib/postgresql/data
```
